
import "@ant-design/v5-patch-for-react-19";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { ReactQueryProvider } from '@/app/(main)/providers/ReactQueryProvider'
import AntdProvider  from './providers/AntdProvider';
import Header from "@/components/layout/Header";
import Sidebar from "@/components/layout/Sidebar";
import Breadcrumbs from "@/components/common/Breadcrumbs";
import {Toaster} from "react-hot-toast";
import {AuthProvider} from "@/contexts/AuthContext";
import { ClassProvider } from '@/contexts/ClassContext';
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
    display: "swap",
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",

};

const RootLayout = ({ children }: React.PropsWithChildren) =>  {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <ReactQueryProvider>
            < AntdProvider>
                <AuthProvider>
                    <ClassProvider>

                <div className="flex flex-col h-screen">
                    <Toaster position="top-right" reverseOrder={false}/>

                    {/* ===== HEADER ===== */}
                    <Header/>

                    {/* ===== BODY ===== */}
                    <div className="flex flex-1 overflow-hidden">
                        {/* SIDEBAR */}
                        <Sidebar/>

                        {/* CONTENT */}
                        <main className="flex-1 p-6 bg-white overflow-y-auto">
                            <Breadcrumbs/>
                            {children}
                        </main>
                    </div>
                </div>
                    </ClassProvider>
                </AuthProvider>
            </AntdProvider>
        </ReactQueryProvider>
        </body>
        </html>
    );
}
export default RootLayout;