// mockQuiz.ts
import type { Quiz, QuizQuestion } from "@/types/quiz";

export const mockQuiz: Quiz = {
    id: "quiz_001",
    classId: "class_01",
    title: "Kiểm tra từ vựng tiếng Anh",
    duration: 15, // phút
    published: true,
    createdBy: "instructor_01",
    createdAt: new Date(),
};
export const mockQuestions: QuizQuestion[] = [
    {
        id: "q1",
        quizId: "quiz_001",
        question: "What is the synonym of 'happy'?",
        options: ["Sad", "Angry", "Joyful", "Tired"],
        correctIndex: 2,
    },
    {
        id: "q2",
        quizId: "quiz_001",
        question: "Choose the correct spelling:",
        options: ["Beautifull", "Beautiful", "Beatiful", "Beautifol"],
        correctIndex: 1,
    },
    {
        id: "q3",
        quizId: "quiz_001",
        question: "Opposite of 'cheap' is?",
        options: ["Expensive", "Small", "Easy", "Fast"],
        correctIndex: 0,
    },
    {
        id: "q4",
        quizId: "quiz_001",
        question: "Which word is a verb?",
        options: ["Run", "Blue", "Happiness", "Quick"],
        correctIndex: 0,
    },
    {
        id: "q5",
        quizId: "quiz_001",
        question: "Plural of 'child' is?",
        options: ["Childs", "Childes", "Children", "Childrens"],
        correctIndex: 2,
    },
    {
        id: "q6",
        quizId: "quiz_001",
        question: "Which one means 'quickly'?",
        options: ["Slow", "Fast", "Late", "Hard"],
        correctIndex: 1,
    },
    {
        id: "q7",
        quizId: "quiz_001",
        question: "Choose the correct sentence:",
        options: [
            "She go to school",
            "She goes to school",
            "She going to school",
            "She gone to school",
        ],
        correctIndex: 1,
    },
    {
        id: "q8",
        quizId: "quiz_001",
        question: "Past tense of 'eat'?",
        options: ["Eated", "Eat", "Ate", "Eating"],
        correctIndex: 2,
    },
    {
        id: "q9",
        quizId: "quiz_001",
        question: "Which is a noun?",
        options: ["Run", "Quick", "Happiness", "Blue"],
        correctIndex: 2,
    },
    {
        id: "q10",
        quizId: "quiz_001",
        question: "Meaning of 'tiny'?",
        options: ["Big", "Small", "Heavy", "Fast"],
        correctIndex: 1,
    },
    {
        id: "q1",
        quizId: "quiz_001",
        question: "What is the synonym of 'happy'?",
        options: ["Sad", "Angry", "Joyful", "Tired"],
        correctIndex: 2,
    },
    {
        id: "q2",
        quizId: "quiz_001",
        question: "Choose the correct spelling:",
        options: ["Beautifull", "Beautiful", "Beatiful", "Beautifol"],
        correctIndex: 1,
    },
    {
        id: "q3",
        quizId: "quiz_001",
        question: "Opposite of 'cheap' is?",
        options: ["Expensive", "Small", "Easy", "Fast"],
        correctIndex: 0,
    },
    {
        id: "q4",
        quizId: "quiz_001",
        question: "Which word is a verb?",
        options: ["Run", "Blue", "Happiness", "Quick"],
        correctIndex: 0,
    },
    {
        id: "q5",
        quizId: "quiz_001",
        question: "Plural of 'child' is?",
        options: ["Childs", "Childes", "Children", "Childrens"],
        correctIndex: 2,
    },
    {
        id: "q6",
        quizId: "quiz_001",
        question: "Which one means 'quickly'?",
        options: ["Slow", "Fast", "Late", "Hard"],
        correctIndex: 1,
    },
    {
        id: "q7",
        quizId: "quiz_001",
        question: "Choose the correct sentence:",
        options: [
            "She go to school",
            "She goes to school",
            "She going to school",
            "She gone to school",
        ],
        correctIndex: 1,
    },
    {
        id: "q8",
        quizId: "quiz_001",
        question: "Past tense of 'eat'?",
        options: ["Eated", "Eat", "Ate", "Eating"],
        correctIndex: 2,
    },
    {
        id: "q9",
        quizId: "quiz_001",
        question: "Which is a noun?",
        options: ["Run", "Quick", "Happiness", "Blue"],
        correctIndex: 2,
    },
    {
        id: "q10",
        quizId: "quiz_001",
        question: "Meaning of 'tiny'?",
        options: ["Big", "Small", "Heavy", "Fast"],
        correctIndex: 1,
    },
    {
        id: "q1",
        quizId: "quiz_001",
        question: "What is the synonym of 'happy'?",
        options: ["Sad", "Angry", "Joyful", "Tired"],
        correctIndex: 2,
    },
    {
        id: "q2",
        quizId: "quiz_001",
        question: "Choose the correct spelling:",
        options: ["Beautifull", "Beautiful", "Beatiful", "Beautifol"],
        correctIndex: 1,
    },
    {
        id: "q3",
        quizId: "quiz_001",
        question: "Opposite of 'cheap' is?",
        options: ["Expensive", "Small", "Easy", "Fast"],
        correctIndex: 0,
    },
    {
        id: "q4",
        quizId: "quiz_001",
        question: "Which word is a verb?",
        options: ["Run", "Blue", "Happiness", "Quick"],
        correctIndex: 0,
    },
    {
        id: "q5",
        quizId: "quiz_001",
        question: "Plural of 'child' is?",
        options: ["Childs", "Childes", "Children", "Childrens"],
        correctIndex: 2,
    },
    {
        id: "q6",
        quizId: "quiz_001",
        question: "Which one means 'quickly'?",
        options: ["Slow", "Fast", "Late", "Hard"],
        correctIndex: 1,
    },
    {
        id: "q7",
        quizId: "quiz_001",
        question: "Choose the correct sentence:",
        options: [
            "She go to school",
            "She goes to school",
            "She going to school",
            "She gone to school",
        ],
        correctIndex: 1,
    },
    {
        id: "q8",
        quizId: "quiz_001",
        question: "Past tense of 'eat'?",
        options: ["Eated", "Eat", "Ate", "Eating"],
        correctIndex: 2,
    },
    {
        id: "q9",
        quizId: "quiz_001",
        question: "Which is a noun?",
        options: ["Run", "Quick", "Happiness", "Blue"],
        correctIndex: 2,
    },
    {
        id: "q10",
        quizId: "quiz_001",
        question: "Meaning of 'tiny'?",
        options: ["Big", "Small", "Heavy", "Fast"],
        correctIndex: 1,
    },
];
