import "@ant-design/v5-patch-for-react-19";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReactQueryProvider } from './providers/ReactQueryProvider'
import { AntdRegistry } from '@ant-design/nextjs-registry';
import Header from "@/components/layout/Header";
import Sidebar from "@/components/layout/Sidebar";
import {Toaster} from "react-hot-toast";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout = ({ children }: React.PropsWithChildren) =>  {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <ReactQueryProvider>
            <AntdRegistry>
                        <div className="flex h-screen">
                            <Toaster position="top-right" reverseOrder={false} />
                            <Sidebar />
                            <div className="flex-1 flex flex-col">
                                <Header />
                                <main className="flex-1 p-6 bg-gray-50">
                                    {children}
                                </main>
                            </div>
                        </div>

            </AntdRegistry>
        </ReactQueryProvider>
        </body>
        </html>
    );
}
export default RootLayout;